/* 
 * Browse API
 *
 * The Browse API has the following resources: item_summary: Lets shoppers search for specific items by keyword, GTIN, category, product, or item aspects and refine the results by using filters. item: Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size. This resource also provides a bridge between the eBay legacy APIs, such as Trading and Finding, and the RESTful APIs, such as Browse, which use different formats for the item IDs. You can use the Browse API to retrieve the basic details of the item and the RESTful item ID using a legacy item ID.
 *
 * OpenAPI spec version: v1_beta.12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SellerLegalInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SellerLegalInfoTests
    {
        // TODO uncomment below to declare an instance variable for SellerLegalInfo
        //private SellerLegalInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SellerLegalInfo
            //instance = new SellerLegalInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SellerLegalInfo
        /// </summary>
        [Test]
        public void SellerLegalInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SellerLegalInfo
            //Assert.IsInstanceOfType<SellerLegalInfo> (instance, "variable 'instance' is a SellerLegalInfo");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'Imprint'
        /// </summary>
        [Test]
        public void ImprintTest()
        {
            // TODO unit test for the property 'Imprint'
        }
        /// <summary>
        /// Test the property 'LegalContactFirstName'
        /// </summary>
        [Test]
        public void LegalContactFirstNameTest()
        {
            // TODO unit test for the property 'LegalContactFirstName'
        }
        /// <summary>
        /// Test the property 'LegalContactLastName'
        /// </summary>
        [Test]
        public void LegalContactLastNameTest()
        {
            // TODO unit test for the property 'LegalContactLastName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Test]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'SellerProvidedLegalAddress'
        /// </summary>
        [Test]
        public void SellerProvidedLegalAddressTest()
        {
            // TODO unit test for the property 'SellerProvidedLegalAddress'
        }
        /// <summary>
        /// Test the property 'TermsOfService'
        /// </summary>
        [Test]
        public void TermsOfServiceTest()
        {
            // TODO unit test for the property 'TermsOfService'
        }
        /// <summary>
        /// Test the property 'VatDetails'
        /// </summary>
        [Test]
        public void VatDetailsTest()
        {
            // TODO unit test for the property 'VatDetails'
        }

    }

}
