/* 
 * Browse API
 *
 * The Browse API has the following resources: item_summary: Lets shoppers search for specific items by keyword, GTIN, category, product, or item aspects and refine the results by using filters. item: Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size. This resource also provides a bridge between the eBay legacy APIs, such as Trading and Finding, and the RESTful APIs, such as Browse, which use different formats for the item IDs. You can use the Browse API to retrieve the basic details of the item and the RESTful item ID using a legacy item ID.
 *
 * OpenAPI spec version: v1_beta.12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShippingOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShippingOptionTests
    {
        // TODO uncomment below to declare an instance variable for ShippingOption
        //private ShippingOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShippingOption
            //instance = new ShippingOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShippingOption
        /// </summary>
        [Test]
        public void ShippingOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShippingOption
            //Assert.IsInstanceOfType<ShippingOption> (instance, "variable 'instance' is a ShippingOption");
        }


        /// <summary>
        /// Test the property 'AdditionalShippingCostPerUnit'
        /// </summary>
        [Test]
        public void AdditionalShippingCostPerUnitTest()
        {
            // TODO unit test for the property 'AdditionalShippingCostPerUnit'
        }
        /// <summary>
        /// Test the property 'CutOffDateUsedForEstimate'
        /// </summary>
        [Test]
        public void CutOffDateUsedForEstimateTest()
        {
            // TODO unit test for the property 'CutOffDateUsedForEstimate'
        }
        /// <summary>
        /// Test the property 'MaxEstimatedDeliveryDate'
        /// </summary>
        [Test]
        public void MaxEstimatedDeliveryDateTest()
        {
            // TODO unit test for the property 'MaxEstimatedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'MinEstimatedDeliveryDate'
        /// </summary>
        [Test]
        public void MinEstimatedDeliveryDateTest()
        {
            // TODO unit test for the property 'MinEstimatedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'QuantityUsedForEstimate'
        /// </summary>
        [Test]
        public void QuantityUsedForEstimateTest()
        {
            // TODO unit test for the property 'QuantityUsedForEstimate'
        }
        /// <summary>
        /// Test the property 'ShippingCarrierCode'
        /// </summary>
        [Test]
        public void ShippingCarrierCodeTest()
        {
            // TODO unit test for the property 'ShippingCarrierCode'
        }
        /// <summary>
        /// Test the property 'ShippingCost'
        /// </summary>
        [Test]
        public void ShippingCostTest()
        {
            // TODO unit test for the property 'ShippingCost'
        }
        /// <summary>
        /// Test the property 'ShippingCostType'
        /// </summary>
        [Test]
        public void ShippingCostTypeTest()
        {
            // TODO unit test for the property 'ShippingCostType'
        }
        /// <summary>
        /// Test the property 'ShippingServiceCode'
        /// </summary>
        [Test]
        public void ShippingServiceCodeTest()
        {
            // TODO unit test for the property 'ShippingServiceCode'
        }
        /// <summary>
        /// Test the property 'ShipToLocationUsedForEstimate'
        /// </summary>
        [Test]
        public void ShipToLocationUsedForEstimateTest()
        {
            // TODO unit test for the property 'ShipToLocationUsedForEstimate'
        }
        /// <summary>
        /// Test the property 'TrademarkSymbol'
        /// </summary>
        [Test]
        public void TrademarkSymbolTest()
        {
            // TODO unit test for the property 'TrademarkSymbol'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
