/* 
 * Buy Marketing API
 *
 * The Marketing API retrieves eBay products based on a metric, such as Best Selling, as well as products that were also bought and also viewed.
 *
 * OpenAPI spec version: v1_beta.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BestSellingProductResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BestSellingProductResponseTests
    {
        // TODO uncomment below to declare an instance variable for BestSellingProductResponse
        //private BestSellingProductResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BestSellingProductResponse
            //instance = new BestSellingProductResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BestSellingProductResponse
        /// </summary>
        [Test]
        public void BestSellingProductResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BestSellingProductResponse
            //Assert.IsInstanceOfType<BestSellingProductResponse> (instance, "variable 'instance' is a BestSellingProductResponse");
        }


        /// <summary>
        /// Test the property 'MerchandisedProducts'
        /// </summary>
        [Test]
        public void MerchandisedProductsTest()
        {
            // TODO unit test for the property 'MerchandisedProducts'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Test]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

    }

}
