/* 
 * Buy Marketing API
 *
 * The Marketing API retrieves eBay products based on a metric, such as Best Selling, as well as products that were also bought and also viewed.
 *
 * OpenAPI spec version: v1_beta.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MarketPriceDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketPriceDetailTests
    {
        // TODO uncomment below to declare an instance variable for MarketPriceDetail
        //private MarketPriceDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketPriceDetail
            //instance = new MarketPriceDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketPriceDetail
        /// </summary>
        [Test]
        public void MarketPriceDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketPriceDetail
            //Assert.IsInstanceOfType<MarketPriceDetail> (instance, "variable 'instance' is a MarketPriceDetail");
        }


        /// <summary>
        /// Test the property 'ConditionGroup'
        /// </summary>
        [Test]
        public void ConditionGroupTest()
        {
            // TODO unit test for the property 'ConditionGroup'
        }
        /// <summary>
        /// Test the property 'ConditionIds'
        /// </summary>
        [Test]
        public void ConditionIdsTest()
        {
            // TODO unit test for the property 'ConditionIds'
        }
        /// <summary>
        /// Test the property 'EstimatedStartPrice'
        /// </summary>
        [Test]
        public void EstimatedStartPriceTest()
        {
            // TODO unit test for the property 'EstimatedStartPrice'
        }

    }

}
