/* 
 * Buy Marketing API
 *
 * The Marketing API retrieves eBay products based on a metric, such as Best Selling, as well as products that were also bought and also viewed.
 *
 * OpenAPI spec version: v1_beta.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MerchandisedProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MerchandisedProductTests
    {
        // TODO uncomment below to declare an instance variable for MerchandisedProduct
        //private MerchandisedProduct instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchandisedProduct
            //instance = new MerchandisedProduct();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchandisedProduct
        /// </summary>
        [Test]
        public void MerchandisedProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MerchandisedProduct
            //Assert.IsInstanceOfType<MerchandisedProduct> (instance, "variable 'instance' is a MerchandisedProduct");
        }


        /// <summary>
        /// Test the property 'AverageRating'
        /// </summary>
        [Test]
        public void AverageRatingTest()
        {
            // TODO unit test for the property 'AverageRating'
        }
        /// <summary>
        /// Test the property 'Epid'
        /// </summary>
        [Test]
        public void EpidTest()
        {
            // TODO unit test for the property 'Epid'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'MarketPriceDetails'
        /// </summary>
        [Test]
        public void MarketPriceDetailsTest()
        {
            // TODO unit test for the property 'MarketPriceDetails'
        }
        /// <summary>
        /// Test the property 'RatingAspects'
        /// </summary>
        [Test]
        public void RatingAspectsTest()
        {
            // TODO unit test for the property 'RatingAspects'
        }
        /// <summary>
        /// Test the property 'RatingCount'
        /// </summary>
        [Test]
        public void RatingCountTest()
        {
            // TODO unit test for the property 'RatingCount'
        }
        /// <summary>
        /// Test the property 'ReviewCount'
        /// </summary>
        [Test]
        public void ReviewCountTest()
        {
            // TODO unit test for the property 'ReviewCount'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
